// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthorizationCode is the predicate function for authorizationcode builders.
type AuthorizationCode func(*sql.Selector)

// OAuthClient is the predicate function for oauthclient builders.
type OAuthClient func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
