// Code generated by ent, DO NOT EDIT.

package authorizationcode

import (
	"time"
)

const (
	// Label holds the string label denoting the authorizationcode type in the database.
	Label = "authorization_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldCodeChallenge holds the string denoting the code_challenge field in the database.
	FieldCodeChallenge = "code_challenge"
	// FieldCodeChallengeMethod holds the string denoting the code_challenge_method field in the database.
	FieldCodeChallengeMethod = "code_challenge_method"
	// FieldIssued holds the string denoting the issued field in the database.
	FieldIssued = "issued"
	// Table holds the table name of the authorizationcode in the database.
	Table = "authorization_codes"
)

// Columns holds all SQL columns for authorizationcode fields.
var Columns = []string{
	FieldID,
	FieldClientID,
	FieldCode,
	FieldCodeChallenge,
	FieldCodeChallengeMethod,
	FieldIssued,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// CodeChallengeValidator is a validator for the "code_challenge" field. It is called by the builders before save.
	CodeChallengeValidator func(string) error
	// CodeChallengeMethodValidator is a validator for the "code_challenge_method" field. It is called by the builders before save.
	CodeChallengeMethodValidator func(string) error
	// DefaultIssued holds the default value on creation for the "issued" field.
	DefaultIssued time.Time
)
