// Code generated by ent, DO NOT EDIT.

package ent

import (
	"auth/ent/oauthclient"
	"auth/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OAuthClientDelete is the builder for deleting a OAuthClient entity.
type OAuthClientDelete struct {
	config
	hooks    []Hook
	mutation *OAuthClientMutation
}

// Where appends a list predicates to the OAuthClientDelete builder.
func (ocd *OAuthClientDelete) Where(ps ...predicate.OAuthClient) *OAuthClientDelete {
	ocd.mutation.Where(ps...)
	return ocd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ocd *OAuthClientDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ocd.hooks) == 0 {
		affected, err = ocd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OAuthClientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ocd.mutation = mutation
			affected, err = ocd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ocd.hooks) - 1; i >= 0; i-- {
			if ocd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ocd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ocd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocd *OAuthClientDelete) ExecX(ctx context.Context) int {
	n, err := ocd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ocd *OAuthClientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: oauthclient.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oauthclient.FieldID,
			},
		},
	}
	if ps := ocd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ocd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// OAuthClientDeleteOne is the builder for deleting a single OAuthClient entity.
type OAuthClientDeleteOne struct {
	ocd *OAuthClientDelete
}

// Exec executes the deletion query.
func (ocdo *OAuthClientDeleteOne) Exec(ctx context.Context) error {
	n, err := ocdo.ocd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthclient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ocdo *OAuthClientDeleteOne) ExecX(ctx context.Context) {
	ocdo.ocd.ExecX(ctx)
}
