// Code generated by ent, DO NOT EDIT.

package oauthclient

const (
	// Label holds the string label denoting the oauthclient type in the database.
	Label = "oauth_client"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClientSecret holds the string denoting the client_secret field in the database.
	FieldClientSecret = "client_secret"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// Table holds the table name of the oauthclient in the database.
	Table = "oauth_clients"
)

// Columns holds all SQL columns for oauthclient fields.
var Columns = []string{
	FieldID,
	FieldClientSecret,
	FieldURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ClientSecretValidator is a validator for the "client_secret" field. It is called by the builders before save.
	ClientSecretValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
)
